---
# This ansible cookbook will update a running pharo app on the server.
# Beware that you need to have a server on which the server-setup.yml cookbook
# has been applied.

- name: <<<< Deploy a new version of the app >>>>
  hosts: web
  remote_user: "{{ deploy_user }}"
  vars_files:
    - vars.yml

  tasks:
    - name: Store the current timestamp
      shell: date '+%F.%H%M%S'
      register: current_time

    - name: Name release directory
      command: echo "{{app_path}}/releases/{{current_time.stdout}}"
      register: release_path

    - name: Create directory for current deploy
      file: path="{{ release_path }}" state=directory recurse=yes

    - name: Get/Update the git repository
      git: repo={{repo}} dest={{repo_path}} accept_hostkey=true

    - name: Copy the content of the repo into the current deploy directory
      shell: cp -r {{repo_path}}/* {{app_path}}/releases/{{current_time.stdout}}

    - name: Copy the pharo virgin image into the deploy directory
      shell: cp {{stock_images_path}}/Pharo-30852.image {{ release_path }}/pharo.image

    - name: Copy the pharo virgin changes into the deploy directory
      shell: cp {{stock_images_path}}/Pharo-30852.changes {{ release_path }}/pharo.changes

    - name: Copy the pharo virgin source into the deploy directory
      shell: cp {{stock_images_path}}/PharoV30.sources {{ release_path }}/PharoV30.sources

    - name: Launch the install script on the fresh image
      shell: "{{ release_path }}/app install"

    # Will throw an error if it is the first deployment or if the pid_file does
    # not exit.
    - name: Stop the current running app
      shell: "{{app_path}}/current/app stop {{pid_file}}"
      ignore_errors: True

    - name: 'Create symbolic link for the current release'
      file: dest={{app_path}}/current src={{ release_path }} state=link

    - name: Start the newly deployed app
      shell: "PHARO_ENV={{ pharo_env }} {{app_path}}/current/app start {{pid_file}}"
