---
# This ansible cookbook will update a running pharo app on the server.
# Beware that you need to have a server on which the server-setup.yml cookbook
# has been applied.

- name: <<<< Deploy a new version of the app >>>>
  hosts: web
  remote_user: {{ deploy_user }}
  vars_files:
    - vars.yml

  tasks:
    - name: Store the current timestamp
      shell: date '+%F.%H%M%S'
      register: current_time

    - name: Create directory for current deploy
      file: path="{{app_path}}/releases/{{current_time.stdout}}" state=directory

    - name: Get/Update the git repository
      git: repo={{repo}} dest={{repo_path}}

    - name: Copy the content of the repo into the current deploy directory
      shell: cp -r {{repo_path}}/* {{app_path}}/releases/{{current_time.stdout}}

    - name: Copy the pharo virgin image into the deploy directory
      shell: cp {{stock_images_path}}/Pharo-30852.image {{app_path}}/releases/{{current_time.stdout}}/pharo.image

    - name: Copy the pharo virgin changes into the deploy directory
      shell: cp {{stock_images_path}}/Pharo-30852.changes {{app_path}}/releases/{{current_time.stdout}}/pharo.changes

    - name: Copy the pharo virgin source into the deploy directory
      shell: cp {{stock_images_path}}/PharoV30.sources {{app_path}}/releases/{{current_time.stdout}}/PharoV30.sources

    - name: Launch the install script on the fresh image
      shell: "{{app_path}}/releases/{{current_time.stdout}}/app install"

    # Will throw an error if it is the first deployment or if the pid_file does
    # not exit.
    - name: Stop the current running app
      shell: "{{app_path}}/current/app stop {{pid_file}}"
      ignore_errors: True

    - name: 'Create symoblic link for the current release'
      file: dest={{app_path}}/current src={{app_path}}/releases/{{current_time.stdout}} state=link

    - name: Start the newly deployed app
      shell: "{{app_path}}/current/app start {{pid_file}}"
      # This is a "fire and forget" command. In the ideal world we should
      # daemonize this...
      # Async the task for 1 year.
      async: 31536000
      poll: 0
