---
# This ansible cookbook will update a running pharo app on the server.
# Beware that you need to have a server on which the server-setup.yml cookbook
# has been applied.

- name: <<<< Deploy a new version of the app >>>>
  hosts: web
  remote_user: azureuser

  vars:
    repo: https://github.com/fstephany/hello-pharo.git
    stock_images_path: /home/{{azureuser}}/stock-images
    app_path: /home/azureuser/apps/hello-pharo
    repo_path: "{{ app_path }}/base-repo"

  tasks:
    - name: Store the current timestamp
      shell: date '+%F.%H:%M:%S'
      register: current_time

    - name: Create directory for current deploy
      file: path="{{ app_path }}/{{ current_time.stdout }}" state=directory

    - name: Get/Update the git repository
      git: repo="{{ repo }}" dest="{{ repo_path }}"

    - name: Copy the content of the repo into the current deploy directory
      file: path="{{ repo_path }}" dest="{{app_path}}/{{ current_time.stdout }}" state=directory recurse=yes

    - name: Copy the pharo virgin image/changes/source into the deploy directory
      file: path="{{ stock_images_path }}"
