---
# This ansible cookbook will setup an Ubuntu server for deploying a Pharo 3.0
# application. When the server is ready, see deploy.yml to actually deploy the
# application.

- name: <<<< Setup a server for Pharo app >>>>
  hosts: web
  remote_user: azureuser
  stock_images_path: /home/{{remote_user}}/stock-images
  image_url: http://files.pharo.org/image/30/latest.zip
  source_url: http://files.pharo.org/sources/PharoV30.sources.zip

  tasks:
    - name: Install Pharo's PPA
      shell: add-apt-repository ppa:pharo/stable
      sudo: yes

    - name: Add i386 architecture (Pharo is 32bits)
      shell: dpkg --add-architecture i386
      sudo: yes

    - name: Update and Dist-upgrade
      apt: update_cache=yes upgrade=dist

    - name: add several users
      apt: pkg={{item}} state=latest update_cache=true
      with_items:
        - git
        - pharo-launcher

    - name: download latest Pharo 3.0 stock-images
      get_url: url={{item}} dest={{stock_images_path}}
      with_items:
        - {{image_url}}
        - {{source_url}}

    - name: unzip image and source files.
      unarchive: src={{item}} dest={{stock_images_path}}
      with_items:
        - {{stock_images_path}}/PharoV30.sources.zip
        - {{stock_images_path}}/latest.zip
