---
# This ansible cookbook will setup an Ubuntu server for deploying a Pharo 3.0
# application. When the server is ready, see deploy.yml to actually deploy the
# application.

- name: <<<< Setup a server for Pharo app >>>>
  hosts: web
  remote_user: azureuser

  vars_files:
    - vars.yml

  tasks:
    - name: Install Pharo's PPA
      apt_repository: repo='ppa:pharo/stable'
      sudo: yes

    - name: Add i386 architecture (Pharo is 32bits)
      shell: dpkg --add-architecture i386
      sudo: yes

    - name: apt update and dist-upgrade
      apt: update_cache=yes upgrade=dist
      sudo: yes

    - name: add necessary packages with apt-get
      apt: pkg={{item}} state=latest update_cache=true
      sudo: yes
      with_items:
        - nginx
        - unzip
        - git
        - pharo-vm-core:i386

    - name: download latest Pharo 3.0 stock-images
      get_url: url={{item}} dest={{stock_images_path}}
      with_items:
        - "{{image_url}}"
        - "{{source_url}}"

    - name: unzip image and source files.
      # -o to force overwrite existing files
      shell: unzip -o {{item}} -d {{stock_images_path}}
      with_items:
        - "{{stock_images_path}}/30852.zip"
        - "{{stock_images_path}}/PharoV30.sources.zip"

    - name: create nginx site configuration file
      action: template src=templates/nginx-site.conf dest=/etc/nginx/sites-available/{{app_name}}.conf
      sudo: yes

    - name: Link app name from sites-available to sites-enabled
      action: file src=/etc/nginx/sites-available/{{app_name}}.conf dest=/etc/nginx/sites-enabled/{{app_name}}.conf state=link
      sudo: yes
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      action: service name=nginx state=restarted

