---
# This ansible cookbook will setup an Ubuntu server for deploying a Pharo 3.0
# application. When the server is ready, see deploy.yml to actually deploy the
# application.

- name: <<<< Setup a server for Pharo app >>>>
  hosts: web
  remote_user: azureuser

  vars:
    stock_images_path: /home/azureuser/stock-images
    image_url: http://files.pharo.org/image/30/latest.zip
    source_url: http://files.pharo.org/sources/PharoV30.sources.zip

  tasks:
    - name: Install Pharo's PPA
      apt_repository: repo='ppa:pharo/stable'
      sudo: yes

    - name: Add i386 architecture (Pharo is 32bits)
      shell: dpkg --add-architecture i386
      sudo: yes

    - name: apt update and dist-upgrade
      apt: update_cache=yes upgrade=dist
      sudo: yes

    - name: add necessary packages with apt-get
      apt: pkg={{item}} state=latest update_cache=true
      sudo: yes
      with_items:
        - nginx
        - git
        - pharo-vm-core
        #- pharo-launcher

    - name: download latest Pharo 3.0 stock-images
      get_url: url={{item}} dest={{stock_images_path}}
      with_items:
        - "{{image_url}}"
        - "{{source_url}}"

    - name: unzip image and source files.
      shell: unzip {{item}} -d {{stock_images_path}}
      with_items:
        - "{{stock_images_path}}/latest.zip"
        - "{{stock_images_path}}/PharoV30.sources.zip"
